services:
  telco-secured.42crunch.test:
    image: 42crunch/apifirewall:latest
    container_name: telco-api-firewall
    ports:
      - "443:443"
    volumes:
      - ./api-firewall/ssl:/opt/guardian/conf/ssl
      - ./api-firewall/LetsEncryptCert:/certs
    command:
      ["/bin/squire", "-platform", "protection.trials.42crunch.com:8001", "-debug"]
    environment:
      - SERVER_NAME=localhost
      - LISTEN_PORT=443
      - PROTECTION_TOKEN=${PROTECTION_TOKEN}
      - GUARDIAN_NODE_NAME=Local-Firewall
      - GUARDIAN_INSTANCE_NAME=Local-Firewall
      - LISTEN_SSL_CERT=firewall-cert.pem
      - LISTEN_SSL_KEY=firewall-key.pem
      - LOG_LEVEL=DEBUG
      - TARGET_URL=https://host.docker.internal:3000/
      - PRESERVE_HOST=ON
    env_file: ".env"
    networks:
      - telco-vulnerable-api_default

networks:
  telco-vulnerable-api_default:
    external: true